var fs = require('fs');
var content = fs.readFileSync('jquery.vmap.thai.js').toString();
var en_province = [
  "Bangkok",
  "Samut Prakan",
  "Nonthaburi",
  "Pathum Thani",
  "Phra Nakhon Si Ayutthaya",
  "Ang Thong",
  "Lop Buri",
  "Sing Buri",
  "Chai Nat",
  "Saraburi",
  "Chon Buri",
  "Rayong",
  "Chanthaburi",
  "Trat",
  "Chachoengsao",
  "Prachin Buri",
  "Nakhon Nayok",
  "Sa Kaeo",
  "Nakhon Ratchasima",
  "Buri Ram",
  "Surin",
  "Si Sa Ket",
  "Ubon Ratchathani",
  "Yasothon",
  "Chaiyaphum",
  "Amnat Charoen",
  "Nong Bua Lam Phu",
  "Khon Kaen",
  "Udon Thani",
  "Loei",
  "Nong Khai",
  "Maha Sarakham",
  "Roi Et",
  "Kalasin",
  "Sakon Nakhon",
  "Nakhon Phanom",
  "Mukdahan",
  "Chiang Mai",
  "Lamphun",
  "Lampang",
  "Uttaradit",
  "Phrae",
  "Nan",
  "Phayao",
  "Chiang Rai",
  "Mae Hong Son",
  "Nakhon Sawan",
  "Uthai Thani",
  "Kamphaeng Phet",
  "Tak",
  "Sukhothai",
  "Phitsanulok",
  "Phichit",
  "Phetchabun",
  "Ratchaburi",
  "Kanchanaburi",
  "Suphan Buri",
  "Nakhon Pathom",
  "Samut Sakhon",
  "Samut Songkhram",
  "Phetchaburi",
  "Prachuap Khiri Khan",
  "Nakhon Si Thammarat",
  "Krabi",
  "Phangnga",
  "Phuket",
  "Surat Thani",
  "Ranong",
  "Chumphon",
  "Songkhla",
  "Satun",
  "Trang",
  "Phatthalung",
  "Pattani",
  "Yala",
  "Narathiwat",
  "Bueng Kan"
];
var th_province = ["กรุงเทพมหานคร",
  "สมุทรปราการ",
  "นนทบุรี",
  "ปทุมธานี",
  "พระนครศรีอยุธยา",
  "อ่างทอง",
  "ลพบุรี",
  "สิงห์บุรี",
  "ชัยนาท",
  "สระบุรี",
  "ชลบุรี",
  "ระยอง",
  "จันทบุรี",
  "ตราด",
  "ฉะเชิงเทรา",
  "ปราจีนบุรี",
  "นครนายก",
  "สระแก้ว",
  "นครราชสีมา",
  "บุรีรัมย์",
  "สุรินทร์",
  "ศรีสะเกษ",
  "อุบลราชธานี",
  "ยโสธร",
  "ชัยภูมิ",
  "อำนาจเจริญ",
  "หนองบัวลำภู",
  "ขอนแก่น",
  "อุดรธานี",
  "เลย",
  "หนองคาย",
  "มหาสารคาม",
  "ร้อยเอ็ด",
  "กาฬสินธุ์",
  "สกลนคร",
  "นครพนม",
  "มุกดาหาร",
  "เชียงใหม่",
  "ลำพูน",
  "ลำปาง",
  "อุตรดิตถ์",
  "แพร่",
  "น่าน",
  "พะเยา",
  "เชียงราย",
  "แม่ฮ่องสอน",
  "นครสวรรค์",
  "อุทัยธานี",
  "กำแพงเพชร",
  "ตาก",
  "สุโขทัย",
  "พิษณุโลก",
  "พิจิตร",
  "เพชรบูรณ์",
  "ราชบุรี",
  "กาญจนบุรี",
  "สุพรรณบุรี",
  "นครปฐม",
  "สมุทรสาคร",
  "สมุทรสงคราม",
  "เพชรบุรี",
  "ประจวบคีรีขันธ์",
  "นครศรีธรรมราช",
  "กระบี่",
  "พังงา",
  "ภูเก็ต",
  "สุราษฎร์ธานี",
  "ระนอง",
  "ชุมพร",
  "สงขลา",
  "สตูล",
  "ตรัง",
  "พัทลุง",
  "ปัตตานี",
  "ยะลา",
  "นราธิวาส",
  "บึงกาฬ"];


for (var i in en_province){
  content = content.replace(en_province[i], th_province[i]);
}

fs.writeFileSync('jquery.vmap.thai2.js', content);